# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'q.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1045, 570)
        MainWindow.setWindowIcon(QtGui.QIcon('Dice.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # Кнопка 1
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 510, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(35)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton.setFont(font)
        self.pushButton.setIconSize(QtCore.QSize(150, 150))
        self.pushButton.setShortcut("")
        self.pushButton.setObjectName("pushButton")
        # Кнопка 2
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton2.setGeometry(QtCore.QRect(980, 510, 40, 40))
        self.pushButton2.setIcon(icon2)
        self.pushButton2.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton2.setFont(font)
        self.pushButton2.setIconSize(QtCore.QSize(150, 150))
        self.pushButton2.setShortcut("")
        self.pushButton2.setObjectName("pushButton")
        # Кнопка 3
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(930, 510, 40, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton3.setIcon(icon3)
        self.pushButton3.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pushButton3.setFont(font)
        self.pushButton3.setIconSize(QtCore.QSize(150, 150))
        self.pushButton3.setShortcut("")
        self.pushButton3.setObjectName("pushButton")
        # Виджеты
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(1, 10, 1040, 115))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(25)
        self.tableWidget.setRowCount(3)
        self.tableWidget2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget2.setGeometry(QtCore.QRect(1, 135, 1040, 115))
        self.tableWidget2.setObjectName("tableWidget")
        self.tableWidget2.setColumnCount(25)
        self.tableWidget2.setRowCount(3)
        self.tableWidget3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget3.setGeometry(QtCore.QRect(1, 260, 1040, 115))
        self.tableWidget3.setObjectName("tableWidget")
        self.tableWidget3.setColumnCount(25)
        self.tableWidget3.setRowCount(3)
        self.tableWidget4 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget4.setGeometry(QtCore.QRect(1, 385, 1042, 115))
        self.tableWidget4.setObjectName("tableWidget")
        self.tableWidget4.setColumnCount(25)
        self.tableWidget4.setRowCount(3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Random"))
        # self.pushButton.setText(_translate("MainWindow", "Пуск"))
        # self.pushButton2.setText(_translate("MainWindow", "Печать"))
        # self.pushButton3.setText(_translate("MainWindow", "Просмотр"))
